### ISSUE TITLE
Clash规则中vmess类型中的servername和network之间缺少逗号进行分隔

### ISSUE THREAD

**Issue by ligongfu** [Project-PMPanel/PMPanel#1]
Clash规则中vmess类型中的servername和network之间缺少逗号进行分隔

附节点配置和出错规则

节点为V2ray，传输协议ws，安全性none

`  - {name: jp, type: vmess, server: jp.com, port: 10002, uuid: 482cddff-745f-39d3-addb-d2296e37180b, alterId: 2, cipher: auto, servername: jp.comnetwork: ws, ws-path: /2, ws-headers: {Host: jp.com}, udp: true}`

**Comment by ByteInternetHK** [comment]
升级版本即可
